<?php

use yii\db\Migration;
use app\commands\templates\MyDbMigration;


class m181218_201510_005_plaza_create extends MyDbMigration
{
   protected $tableName='rh_plaza';
/*
    public function up()
    {

    }

    public function down()
    {

    }
*/

    // Use safeUp/safeDown to run migration code within a transaction
    public function safeUp()
    {
      switch ($this->driver) {
        case 'sqlite':
          $this->_safeUp_sqlite();
          break;
        case 'mysql':
          $this->_safeUp_mysql();
          break;
        default:
      }
    }

    public function safeDown()
    {
      switch ($this->driver) {
        case 'sqlite':
          $this->_safeDown_sqlite();
          break;
        case 'mysql':
          $this->_safeDown_mysql();
          break;
        default:
      }
    }

    public function _safeUp_sqlite()
    {
        $this->createTable($this->tableName, [
            'id'            => 'INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT',
            'clave'         => 'VARCHAR(31) NOT NULL',
            'descr'         => 'VARCHAR(35)',
            'tipo'          => "VARCHAR(10) NOT NULL DEFAULT 'TEMPORAL'",
            'clave_puesto'  => 'INTEGER UNSGINED NOT NULL REFERENCES rh_puesto(clave)',
            'activa'        => 'TINYINT UNSIGNED NOT NULL DEFAULT 1',
            'visible'       => 'TINYINT UNSIGNED NOT NULL DEFAULT 1',
            'depto'         => 'INTEGER UNSIGNED',
            'clave_descanso'=> 'CHAR(2) NOT NULL REFERENCES rh_descanso(clave)',
            'clave_jornada' => 'INTEGER UNSIGNED NOT NULL REFERENCES rh_jornada(clave)',
            'fec_creacion'  => 'DATETIME',
            'residencia'    => 'VARCHAR(60)',
            'localidad'     => 'VARCHAR(60)',
            'taller'        => 'VARCHAR(60)',
            'instalacion'   => 'VARCHAR(60)',
            'funcion'       => 'VARCHAR(60)',
            'actividad'     => 'VARCHAR(60)',
            'grupo'         => 'VARCHAR(40)',
            'sirhn'         => 'INTEGER UNSIGNED',
            'posfin'        => 'INTEGER UNSIGNED',
            'escalafon'     => 'INTEGER UNSIGNED',
        ]);
        $this->insertRows();
    }

    public function _safeUp_mysql()
    {
        $this->createTable($this->tableName, [
            'id'            => $this->primaryKey(),
            'clave'         => $this->string(30)->notNull(),
            'descr'         => $this->string(35),
            'tipo'          => "ENUM('DEFINITIVA', 'TEMPORAL') DEFAULT 'TEMPORAL'",
            'clave_puesto'  => $this->integer()->unsigned()->notNull(),
            'activa'        => $this->tinyInteger()->notNull()->defaultValue(1),
            'visible'       => $this->tinyInteger()->notNull()->defaultValue(1),
            'depto'         => $this->integer()->unsigned(),
            'clave_descanso'=> $this->char(2)->notNull(),
            'clave_jornada' => $this->integer()->unsigned()->notNull(),
            'fec_creacion'  => $this->date(),
            'residencia'    => $this->string(60),
            'localidad'     => $this->string(60),
            'taller'        => $this->string(60),
            'instalacion'   => $this->string(60),
            'funcion'      => $this->string(60),
            'actividad'     => $this->string(60),
            'grupo'         => $this->string(40),
            'sirhn'         => $this->integer()->unsigned(),
            'posfin'        => $this->integer()->unsigned(),
            'escalafon'     => $this->integer()->unsigned(),
        ]);
        $this->createIndex('IDX_CLAVE_PLAZA', $this->tableName, 'clave');
        $this->createIndex('IDX_CLAVE_DESCANSO', $this->tableName, 'clave_descanso');
        $this->createIndex('IDX_CLAVE_JORNADA', $this->tableName, 'clave_jornada');
        $this->createIndex('IDX_CLAVE_PUESTO', $this->tableName, 'clave_puesto');

        $this->addForeignKey('FK_CLAVE_DESCANSO', $this->tableName, 'clave_descanso', 'rh_descanso', ['clave'], 'CASCADE', 'NO ACTION');
        $this->addForeignKey('FK_CLAVE_JORNADA', $this->tableName, 'clave_jornada', 'rh_jornada', ['clave'], 'CASCADE', 'NO ACTION');
        $this->addForeignKey('FK_CLAVE_PUESTO', $this->tableName, 'clave_puesto', 'rh_puesto', ['clave'], 'CASCADE', 'NO ACTION');
        $this->insertRows();
    }

    public function _safeDown_sqlite()
    {
        $this->dropTable($this->tableName);
    }

    public function _safeDown_mysql()
    {
        $this->dropForeignKey('FK_CLAVE_DESCANSO', $this->tableName);
        $this->dropForeignKey('FK_CLAVE_JORNADA', $this->tableName);
        $this->dropForeignKey('FK_CLAVE_PUESTO', $this->tableName);
        $this->dropIndex('IDX_CLAVE_DESCANSO', $this->tableName);
        $this->dropIndex('IDX_CLAVE_JORNADA', $this->tableName);
        $this->dropIndex('IDX_CLAVE_PUESTO', $this->tableName);
        $this->dropIndex('IDX_CLAVE_PLAZA', $this->tableName);
        $this->dropTable($this->tableName);
    }


    public function insertRows()
    {

                    $this->insert($this->tableName, ['clave'=>'24028400 00001', 'descr'=>'AUXILIAR ADMINISTRATIVO "F" ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>221804, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>41610, 'posfin'=>41610, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00031', 'descr'=>'OFICINISTA DE CUARTA ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>164406, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>36578, 'posfin'=>36578, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00090', 'descr'=>'OFICINISTA DE CUARTA ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>164406, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>36574, 'posfin'=>36574, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00027', 'descr'=>'OPERARIO DE PRIMERA (ELECTRICISTA) ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>216309, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'TALLERES', 'sirhn'=>36768, 'posfin'=>36768, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00024', 'descr'=>'OPERARIO ESPECIALISTA (ELECTRICISTA) ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>236309, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'TALLERES', 'sirhn'=>36999, 'posfin'=>36999, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00102', 'descr'=>'OBRERO GENERAL ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>37164, 'posfin'=>37164, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00106', 'descr'=>'OBRERO GENERAL ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>37166, 'posfin'=>37166, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00099', 'descr'=>'OBRERO GENERAL ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>37733, 'posfin'=>37733, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00107', 'descr'=>'OBRERO GENERAL ', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'EBANO', 'taller'=>null, 'instalacion'=>null, 'funcion'=>null, 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>37158, 'posfin'=>37158, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24025500 60000', 'descr'=>'AUXILIAR ADMINISTRATIVO “D”', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>241804, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. LIQUIDOS', 'grupo'=>'ADMVO', 'sirhn'=>20858741, 'posfin'=>20858741, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00008', 'descr'=>'AUXILIAR ADMINISTRATIVO “D”', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>241804, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>null, 'grupo'=>'ADMVO', 'sirhn'=>20858024, 'posfin'=>20858024, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 00001', 'descr'=>'OPERADOR “A” DE CAPTURA DE DATOS', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>232907, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'ADMVO', 'sirhn'=>20858035, 'posfin'=>20858035, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00004', 'descr'=>'ENCARGADO “D” (OTROS)', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>209601, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>null, 'grupo'=>'ADMVO', 'sirhn'=>20857955, 'posfin'=>20857955, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00005', 'descr'=>'OFICINISTA DE TERCERA', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>184406, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'ADMVO', 'sirhn'=>20857935, 'posfin'=>20857935, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'112410002AL 20903338', 'descr'=>'ESPECIALISTA TÉCNICO "D"', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>331102, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>null, 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'ADMINISTRACION', 'grupo'=>'ADMVO', 'sirhn'=>20903338, 'posfin'=>20903338, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028900 60000', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>291710, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'OFICINA LOGISTICA', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'ADMINISTRACION', 'grupo'=>'ADMVO', 'sirhn'=>20864044, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00007', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>232907, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'ADMINISTRACION', 'grupo'=>'ADMVO', 'sirhn'=>20858033, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 00003', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>184406, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'OFICINA LOGISTICA', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'ADMINISTRACION', 'grupo'=>'ADMVO', 'sirhn'=>20857934, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10001', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>268101, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'V', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'OFICINA LOGISTICA', 'funcion'=>'MANDO MEDIO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'MANDO', 'sirhn'=>20858038, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10002', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>255211, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'S', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'MANDO MEDIO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'MANDO', 'sirhn'=>20858094, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2402890030 04025', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>235209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20869174, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10003', 'descr'=>'EQUIPO PESADO', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>235209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'V', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857967, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10004', 'descr'=>'EQUIPO PESADO', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>235209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'J', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857970, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10005', 'descr'=>'EQUIPO PESADO', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>235209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857961, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10006', 'descr'=>'EQUIPO PESADO', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>235209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'V', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857968, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 30303', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>227201, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858028, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 00005', 'descr'=>'MOVIMIENTOS', 'tipo'=>'TEMPORAL', 'clave_puesto'=>216203, 'activa'=>0, 'visible'=>0, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 93001', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>216203, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'X', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20857969, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 31012', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>216202, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'CACALILAO', 'instalacion'=>'PLANTA CENTRAL', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20857958, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 94100', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>216202, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'PLANTA CENTRAL', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20857971, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10007', 'descr'=>'INSTL. DE PRODUCCIÓN', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'TALLER PRODUCCIÓN', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857926, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10008', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857928, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10009', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857931, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10010', 'descr'=>'BATS. Y CARGADEROS PANUCO', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'PANUCO', 'instalacion'=>'EST. SAN MANUEL', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. LIQUIDOS', 'grupo'=>'PESADO', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10011', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'TALLER PRODUCCION', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857927, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10012', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'S', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'CPO. TAMPS.', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857925, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10013', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'TALLER PRODUCCIÓN', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857906, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10014', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>176202, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER ELECTRICO', 'funcion'=>'SEMI-PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20857903, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2402890030 04026', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>116209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20869175, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402890030 04027', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>116209, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'CACALILAO', 'instalacion'=>'PLANTA CENTRAL', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20869183, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 00007', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>86107, 'activa'=>0, 'visible'=>0, 'depto'=>null, 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'CACALILAO', 'instalacion'=>'TALLERES PRODUCCION', 'funcion'=>'GENERAL', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 00604', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20858125, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10037', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'V', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858150, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10038', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858149, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10039', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858148, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10040', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'V', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858146, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10041', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10042', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'X', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858143, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10043', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>'PESADO', 'sirhn'=>20858142, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 30301', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20858174, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2402860030 31129', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>86107, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'J', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>'PESADO', 'sirhn'=>20858173, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040797', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>228101, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>4, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040798', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>228101, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>4, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10016', 'descr'=>'RUTA FIJA BOMB. TAMPS.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'J', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857870, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10017', 'descr'=>'RUTA FIJA BOMB. CONST.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'X', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857871, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10023', 'descr'=>'RUTA FIJA PLANTA DE INYECCION', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'J', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857895, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10024', 'descr'=>'RUTA FIJA PLANTA DE INYECCION', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857890, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10025', 'descr'=>'RUTA FIJA BOMB. CONST.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'L', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857876, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10026', 'descr'=>'RUTA FIJA BOMB. CONST.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'V', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857868, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10027', 'descr'=>'RUTA FIJA BOMB. TAMPS.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857889, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10028', 'descr'=>'RUTA PLANTA DE INYECCION', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10030', 'descr'=>'RUTA PM-5603', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10031', 'descr'=>'RUTA PM-5603', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10032', 'descr'=>'RUTA FIJA RELEVO BOMB. TAMPS/BOMB. CONST.', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857892, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10033', 'descr'=>'RUTA BOMB. CONST.', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10035', 'descr'=>'RUTA FIJA RELEVO PLANTA INYECC/COMPRESORAS III', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857894, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10036', 'descr'=>'RUTA VIJA BOMB. TAMPS', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'GUARDIAS', 'sirhn'=>20857888, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00030503', 'descr'=>'RUTA VARIABLE CR', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20859468, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00050901', 'descr'=>'RUTA COMPRESORAS III', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'L', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20861497, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00050904', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>5, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20861600, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025020', 'descr'=>'RUTA VARIABLE PM-5521', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'L', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20873539, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025021', 'descr'=>'RUTA COMPRESORAS III', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'X', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20873540, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025023', 'descr'=>'RUTA COMPRESORAS III', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20873541, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025024', 'descr'=>'RUTA VARIABLE CR', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'M', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20873542, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025025', 'descr'=>'RUTA VARIABLE PM-1312', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'J', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20873543, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040793', 'descr'=>'RUTA PLANTA DE INYECCION', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20877252, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040796', 'descr'=>'RUTA VARIABLE RELEVO 5521/CR', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>2, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DESPACHO DE GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>'GUARDIAS', 'sirhn'=>20877253, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10015', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'EBANO', 'instalacion'=>'OFICINAS DE OPN. DE POZOS', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857869, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10018', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857872, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10019', 'descr'=>'PLANTA CENTRAL', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'PACAEB', 'taller'=>'CACALILAO', 'instalacion'=>'PLANTA CENTRAL', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857873, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10020', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857874, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10021', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857875, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10022', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857896, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10029', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857891, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028600 10034', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'TALLER LOGISTICA', 'funcion'=>'CHOFER', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>'CHOFERES', 'sirhn'=>20857893, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00047', 'descr'=>'CORROSIÓN', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>178502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DUCTOS Y VIAS DE ACCESO', 'funcion'=>'SEMI-PESADO', 'actividad'=>'ASSIGN', 'grupo'=>'ASIGN', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24027200 00007', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23872000', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'SERVICIOS GENERALES', 'funcion'=>'CHOFER', 'actividad'=>'ASSIGN', 'grupo'=>'ASIGN', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24027200 00029', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23872000', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'ALMACEN', 'funcion'=>'CHOFER', 'actividad'=>'ASSIGN', 'grupo'=>'ASIGN', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'2402890030 04050', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>null, 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'CD. MADERO', 'taller'=>'SECTOR ARENQUE', 'instalacion'=>'BAT. ARENQUE', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>'CHOFERES', 'sirhn'=>20855184, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00064', 'descr'=>'TANQUES Y TUBERIAS', 'tipo'=>'DEFINITIVA', 'clave_puesto'=>156207, 'activa'=>1, 'visible'=>1, 'depto'=>'23816002', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'DUCTOS Y VIAS DE ACCESO', 'funcion'=>'CHOFER', 'actividad'=>'ASSIGN', 'grupo'=>'ASIGN', 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00081', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>216203, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'OFICINA LOGISTICA', 'funcion'=>'PESADO', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24027200 00030', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23872000', 'clave_descanso'=>'V', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00030501', 'descr'=>'RUTA PM-5521', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00030502', 'descr'=>'RUTA PM-5521', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00050902', 'descr'=>'RUTA DCM-722', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 00050903', 'descr'=>'RUTA DCM-722', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'S', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'ECOLOGIA', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025022', 'descr'=>'RUTA DS-663', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10025076', 'descr'=>'RUTA DS-664', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040790', 'descr'=>'RUTA DS-665', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040791', 'descr'=>'RUTA DS-665', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040792', 'descr'=>'RUTA DS-665', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040794', 'descr'=>'RUTA DS-667', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'2381610030 10040795', 'descr'=>'RUTA DS-667', 'tipo'=>'TEMPORAL', 'clave_puesto'=>158502, 'activa'=>0, 'visible'=>0, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>1, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'GUARDIAS', 'funcion'=>'GUARDIAS', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00065', 'descr'=>null, 'tipo'=>'TEMPORAL', 'clave_puesto'=>156207, 'activa'=>0, 'visible'=>0, 'depto'=>'23816002', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>null, 'taller'=>null, 'instalacion'=>null, 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>null, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'24028600 00002', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>221804, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'ADMINISTRACION', 'grupo'=>null, 'sirhn'=>20858009, 'posfin'=>null, 'escalafon'=>10]);
                    $this->insert($this->tableName, ['clave'=>'24028500 00009', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>243513, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. LIQUIDOS', 'grupo'=>null, 'sirhn'=>20858022, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'82024910 00001', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'TAMPICO', 'instalacion'=>'EDIFICIO AGUILA', 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>20858746, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'82024961 00011', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'TAMPICO', 'instalacion'=>null, 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>20858751, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'82024981 00003', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>158502, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'D', 'clave_jornada'=>7, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'TAMPICO', 'instalacion'=>null, 'funcion'=>'CHOFER', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>20858756, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'82024901 00003', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>234406, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'TAMPICO', 'instalacion'=>null, 'funcion'=>'ADMINISTRATIVO', 'actividad'=>null, 'grupo'=>null, 'sirhn'=>20858765, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'112410002AL 20903229', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>371102, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. LIQUIDOS', 'grupo'=>null, 'sirhn'=>20903229, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'112410002AL 20903304', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>351102, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. MATERIALES', 'grupo'=>null, 'sirhn'=>20903304, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'20926100PR 10073243', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>331102, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. PERSONAL', 'grupo'=>null, 'sirhn'=>20903338, 'posfin'=>null, 'escalafon'=>null]);
                    $this->insert($this->tableName, ['clave'=>'23816002AL 00190731', 'descr'=>null, 'tipo'=>'DEFINITIVA', 'clave_puesto'=>331102, 'activa'=>1, 'visible'=>1, 'depto'=>'23816100', 'clave_descanso'=>'SD', 'clave_jornada'=>0, 'residencia'=>null, 'localidad'=>'ALTAMIRA', 'taller'=>'CAMPO TAMAULIPAS', 'instalacion'=>'EDIFICIO ADMINISTRATIVO', 'funcion'=>'ADMINISTRATIVO', 'actividad'=>'TRANSP. LIQUIDOS', 'grupo'=>null, 'sirhn'=>20903229, 'posfin'=>null, 'escalafon'=>null]);

    }
}
